### ISSUE TITLE
Doesn't build for me - SBCL 1.4.3

### ISSUE THREAD

**Issue by xach** [TBRSS/overlord#1]
Hi, I get this:

    ; caught WARNING:
    ;   Can't tell if FUNCTION-ALIAS is a subtype of IMPORT-SPEC. Is IMPORT-SPEC defined?
    ; 
    ; caught WARNING:
    ;   Can't tell if MACRO-ALIAS is a subtype of IMPORT-SPEC. Is IMPORT-SPEC defined?
    ; 
    ; caught WARNING:
    ;   Can't tell if (TUPLE SYMBOL :AS IMPORT-ALIAS) is a subtype of IMPORT-SPEC. Is IMPORT-SPEC defined?
    Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001DB0083}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "overlord/import-set" "lisp">

Worked fine 24 hours ago.

**Comment by ruricolist** [comment]
I've reverted the offending commit.
