### ISSUE TITLE
Is this correct? 

### ISSUE THREAD

**Issue by K1D77A** [TBRSS/overlord#26]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/10334164/200386304-4062a6be-5693-480f-873d-c410d46cf274.png">

Is this correct behaviour? 
I am using cl-yesql. 

Thanks.

**Comment by ruricolist** [comment]
That's the intended behavior. A persistent thread pool with one thread per core is created during the first build to read metadata from the file system. You can suppress it with `(setf (overlord:use-threads-p) nil)`.

**Comment by K1D77A** [comment]
Thanks :)
