### ISSUE TITLE
BUILD all modules from a given package

### ISSUE THREAD

**Issue by phoe** [TBRSS/overlord#4]
I have code like:

```lisp
(in-package :my-package)
(overlord:import foo ...)
(overlord:import bar ...)
(overlord:import baz ...)
```

I would like to have a possibility to call a function like `(overlord:build-all-from-package :my-package)` which will rebuild `FOO`, `BAR`, and `BAZ` for me at once.

In other words - I want to have a possibility to rebuild all modules denoted by symbols from the package I supply.

In yet another words - I would like to have something like `OVERLORD:BUILD-ALL` that will automatically pick up changes that I made in the files and will recompile the proper files.

**Comment by ruricolist** [comment]
There's no way yet to build just the targets defined in a package, but you can build all targets by calling `build` with no arguments.

**Comment by phoe** [comment]
Do you store the symbols somewhere? If yes, then you could expose that symbol store and I could satisfy my request by going `(build (remove-if-not ...))`

`build` with no arguments is good enough though.
