### ISSUE TITLE
#+() is dangerous

### ISSUE THREAD

**Issue by phoe** [TBRSS/overlord#6]
https://github.com/TBRSS/overlord/blob/a2380a4b4638be7d5220b3df7665e09ca2f1ff71/importing.lisp#L156

`#+()` is in fact `#+NIL` and will trigger if someone pushes `NIL` into `*FEATURES*`.

Please replace it with `#+(or)` which is guaranteed to never fire.

**Comment by ruricolist** [comment]
Solved by #7.
